name: Pipeline CI

on:
  push:

  workflow_dispatch:

  schedule:
    - cron: '23 22 * * *'

jobs:

  testes:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Instalar dependências
      run: npm ci

    - name: Executar testes
      run: npm test

    - name: Publicar relatório
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-testes
        path: mochawesome-report/